services:
  - type: web
    name: sams-api
    runtime: node
    plan: starter
    buildCommand: |
      pnpm install
      pnpm build
      pnpm --filter @sams/api exec prisma migrate deploy
    startCommand: cd apps/api && pnpm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: sams-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: CORS_ORIGIN
        value: https://sams-web-emwb.onrender.com

  - type: web
    name: sams-web
    runtime: static
    buildCommand: corepack enable && pnpm install --frozen-lockfile=false && pnpm --filter @sams/web build
    staticPublishPath: apps/web/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://sams-api-vfvj.onrender.com/api

databases:
  - name: sams-postgres
    plan: basic-1gb
    databaseName: sams_prod
    user: sams_user
